sudo: required
env:
  - CABALVER=1.22 GHCVER=7.10.2

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal update
 - cabal install alex happy
 - export PATH=~/.cabal/bin:$PATH

script:
  - make
  
