language: haskell
ghc:
  - "8.4.1"

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install alex-3.1.7 happy-1.19.5 cabal-install-2.0 ghc-$GHCVER
 - export PATH=/opt/cabal/2.0/bin:/opt/ghc/$GHCVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

script:
  - make
  
